### ISSUE TITLE
As a user, I want to view the custom standings so I can see what place my team is in

### ISSUE THREAD

**Issue by ryanMcNierney** [ryanMcNierney/shakeup2019#2]
## User Story
As a user, I want to view the custom standings so I can see what place my team is in. I do not need to be logged in to view this data

## Required Work
- [x] New _standings_ model for db #8
- [x] New _teams_ model for db #9
- [x] Persistent working yahoo _access_token_ #3
- [x] API route to pull current teams from the Yahoo API #10
- [x] API route to pull current standings from the Yahoo API #4
- [x] Update the standings to include custom Top 6 scoring #5
- [x] Update and save the standings in _standings_  table in the DB #6
- [x] API route to pull current standings from DB #7
- [x] Job to update standings every Tuesday morning
- [x] Front-end to display current standings to the user on the homepage

## Acceptance Criteria
As a logged out user, I can go to the homepage and see the current league standings
